dist:     trusty
sudo:     false
language: sh

matrix:
  include:
    - os: linux
      addons: { apt: { packages: [cabal-install-1.24, ghc-8.0.1], sources: [hvr-ghc] } }
    - os: osx

cache:
  directories:
    - $HOME/.opam
    - $TRAVIS_BUILD_DIR/coq
    - $TRAVIS_BUILD_DIR/coq-serapi
    - $TRAVIS_BUILD_DIR/opam

before_install:
  - export $(./.travis-$TRAVIS_OS_NAME.sh export)
  - ./.travis-$TRAVIS_OS_NAME.sh before_install
  - opam init --no-setup
  - opam switch 4.02.3
  - eval `opam config env`
  - opam install --yes camlp5 ocamlfind ppx_import cmdliner core_kernel sexplib ppx_sexp_conv

install:
  - ./setup-coq.sh
  - which coqc
  - make
